modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/Gegy/whats-that-slot"
displayTest = "IGNORE_ALL_VERSION"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "What's That Slot"
authors = "Gegy"
description = '''
Utility that highlights which items can be placed in an item slot while holding down Left Alt.'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
